wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.25
    code_path: code/main.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.5
    t:
      1:
      - 1
      4: 3.6.5
      5: 0.10.25
      8:
      - 3
      - 5
    visualize:
      lenet_regulizedAcc:
        panel_config:
          fieldSettings:
            stroke: null
            x: epoch
            y: lenet_regulizedAcc
          panelDefId: wandb/line/v0
          stringSettings:
            title: lenet_regulizedAcc graph
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - args:
              - name: runSets
                value: ${runSets}
              fields:
              - fields: []
                name: id
              - fields: []
                name: name
              - fields: []
                name: _defaultColorIndex
              - args:
                - name: tableKey
                  value: lenet_regulizedAcc_table
                fields: []
                name: summaryTable
              name: runSets
        panel_type: Vega2
      lenet_regulizedloss:
        panel_config:
          fieldSettings:
            stroke: null
            x: epoch
            y: lenet_regulizedloss
          panelDefId: wandb/line/v0
          stringSettings:
            title: lenet_regulizedloss graph
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - args:
              - name: runSets
                value: ${runSets}
              fields:
              - fields: []
                name: id
              - fields: []
                name: name
              - fields: []
                name: _defaultColorIndex
              - args:
                - name: tableKey
                  value: lenet_regulizedloss_table
                fields: []
                name: summaryTable
              name: runSets
        panel_type: Vega2
